### ISSUE TITLE
LinkedList 是双向链表吧，第一个节点的 prev 指向 null，最后一个节点的 next 指向 null

### ISSUE THREAD

**Issue by 1332508387** [crossoverJie/Java-Interview#28]

**Comment by crossoverJie** [comment]
@1332508387 多谢提醒。
刚才仔细看了下源码，在 1.7 中确实不是循环链表，最后一个指向的 `null`

![](https://ws1.sinaimg.cn/large/006tKfTcly1fqzaf6egnzj30x60f4q4q.jpg)

等会调整下。
