### ISSUE TITLE
BinaryNode.java咨询

### ISSUE THREAD

**Issue by PYTWSW** [crossoverJie/Java-Interview#36]
你好，我正在学习JAVA中，在BinaryNode.java中写好那些函数的功能之后，怎样在主函数中实现一个实例呢？我不会写。

**Comment by crossoverJie** [comment]
https://github.com/crossoverJie/Java-Interview/blob/9499cda4d05a82996d9c82d56c0a5644f6257785/src/test/java/com/crossoverjie/algorithm/BinaryNodeTest.java#L8-L17

@PYTWSW 参考这里

**Comment by PYTWSW** [comment]
谢了！

**Comment by crossoverJie** [comment]
@PYTWSW 

没事。
没有问题我就先 close 了。
