### ISSUE TITLE
LinkedList 底层分析 疑问

### ISSUE THREAD

**Issue by shichaohao** [crossoverJie/Java-Interview#45]
LinkedList 底层分析 中的查询方法写着“使用二分查找”。严格来说，并不是二分查找，因为二分查找每一次都会减半搜索空间。（详见 https://zh.wikipedia.org/wiki/%E4%BA%8C%E5%88%86%E6%90%9C%E7%B4%A2%E7%AE%97%E6%B3%95）

**Comment by crossoverJie** [comment]
@shichaohao 

嗯 描述不是很准确，只是第一次分了。

欢迎提 PR 一起完善。

**Comment by shichaohao** [comment]
我也不知道这种术语该是什么。。。就不提pr了。
