### ISSUE TITLE
关于ThreadPoolExecutor源码解释的几点疑问。

### ISSUE THREAD

**Issue by Sortinn** [crossoverJie/Java-Interview#83]
<img width="956" alt="2018-08-04 7 27 53" src="https://user-images.githubusercontent.com/23185249/43676065-8175f772-981c-11e8-827e-c777cf64e662.png">

**上图为您`ThreadPoolExecutor.md`中`execute()`函数解释部分的内容**，对照源码读到这里的时候产生了几点小疑问，希望您能帮我解答一下。

- 疑问1：图中第4点“尝试判断线程是否全部执行完毕”在代码中是如何体现的呀？这里我想了您写这个判断也许是因为`execute()`方法的comments中提到了
>So we recheck state and if necessary roll back the enqueuing if stopped ...(line 1347 ~ 1379)

因为我在代码中没有看到这个判断，所以有这个疑问；

- 疑问2：图中第6点，这个`else if`是和第三点的`if`同级的条件语句，执行该语句的原因您指出为“在第三步的判断为非运行状态”。因为第三点的`if`语句中包括两个条件，您默认线程是非运行状态的会执行该`else if`语句，那会不会有当前线程仍是运行的状态但调用`offer()`方法失败的情况呢？如果是入队失败的原因，新建线程调用addWorker()方法会将该任务作为第一个任务执行，这样会对现在线程池产生什么影响呢？还是这种可能性不存在呢？

希望得到您的解答，THX~

**Comment by crossoverJie** [comment]
看得很仔细👍。

**第一个问题：**

![](https://ws4.sinaimg.cn/large/0069RVTdgy1ftxzvb9vouj30nc02xjrt.jpg)

`remove()` 方法中的 `tryTerminate` 就是 **“尝试判断线程是否全部执行完毕”**，可以点进去看下源码。

**第二个问题：**

肯定会有是运行状态但是写入失败的情况，这种一般是队列满了。

这样其实在调用 `addWork()`:

![](https://ws4.sinaimg.cn/large/0069RVTdly1fty1ipl2qgj30io02aaa4.jpg)

成功了，会执行 start。

但执行 start 并不是直接执行当前写入的线程。

而是会调用 Worker 类的 run 方法。

![](https://ws1.sinaimg.cn/large/0069RVTdly1fty1kqgykhj30en01st8p.jpg)

这个方法会去队列里面取出任务然后真正的执行。

![](https://ws2.sinaimg.cn/large/0069RVTdly1fty1m362umj30sw0m4aef.jpg)

`getTask()` 就是在队列里取任务。

**Comment by Sortinn** [comment]
多谢解答，谢谢您🙏 高天 邮箱：sortinndecar@gmail.com 签名由 网易邮箱大师 定制 在2018年08月04日 22:39，crossoverJie 写道： 看得很仔细👍。 第一个问题： remove() 方法中的 tryTerminate 就是 “尝试判断线程是否全部执行完毕”，可以点进去看下源码。 第二个问题： 肯定会有是运行状态但是写入失败的情况，这种一般是队列满了。 这样其实在调用 addWork(): 成功了，会执行 start。 但执行 start 并不是直接执行当前写入的线程。 而是会调用 Worker 类的 run 方法。 这个方法会去队列里面取出任务然后真正的执行。 getTask() 就是在队列里取任务。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
